name: seller_app
description: "تطبيق البائع - نظام إدارة المخزون"
publish_to: 'none'

version: 1.0.4+5

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.5

  # HTTP & API
  dio: ^5.9.0

  # Storage
  shared_preferences: ^2.5.3

  # Location
  geolocator: ^14.0.2

  # UI
  google_fonts: ^6.2.1
  flutter_spinkit: ^5.2.2

  # Utils
  intl: ^0.20.2
  connectivity_plus: ^7.0.0
  uuid: ^4.5.2
  url_launcher: ^6.2.5

  # Printing
  printing: ^5.13.4
  pdf: ^3.11.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.4.3
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/Nobg.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/Nobg.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/Nobg.png

